version = 1

[[annotations]]
path = [
    ".gitignore",
    ".python-version",
    ".releaserc.json",
    "pyproject.toml",
    "uv.lock",
    "CHANGELOG.md",
    "LICENSE.md",
    "README.md",
    "README_TEMPLATE.md",
    ".github/images/**",
]
SPDX-FileCopyrightText = "[year] Author Name <author@example.com>"
SPDX-License-Identifier = "ISC"
